
---
title: "main.r"
author: "JohnHadish"
date: "3/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Testing The Program:
Each Function should have its own demonstration script: 

Download Data:
```{r}
myGenotype=read.table(file="http://zzlab.net/GAPIT/data/mdp_numeric.txt",head=T)
myPosition=read.table(file="http://zzlab.net/GAPIT/data/mdp_SNP_information.txt",head=T)
myPhenotype=read.table(file="http://zzlab.net/GAPIT/data/CROP545_Phenotype.txt",head=T)
myCovariate=read.table(file="http://zzlab.net/GAPIT/data/CROP545_Covariates.txt",head=T)
```

```{r}
library(plotly)
library(ggplot2)
library(gridExtra)
library(knitr)

# NOT WORKING YET, CANNOT FIND NAME SPACES FROM REMOTE INSTALL
library(devtools)
install_github("JohnHadish/Crop545HW4")
library("Crop545HW4")
```

Description: 
returns: P: a vector n long of p values for every gene in n
Dependent: Generate_PCA, Scree, Determine_Linear_Dependent
```{r, Run_GLM}
# prcomp is a default principle component analysis
allPC <- prcomp(myGenotype[,-1])
# pcThreshold removes all princople components that account for less than threshold
threshPC <- pcThreshold(allPC)

# pcCovariance  determines if covariates are linear with principle components
finalPC <- pcCoVariance(threshPC, myCovariate, .7)

P <- Run_GLM(myGenotype, myPhenotype[,2], finalPC)

P2 <- GWASbyCor(myGenotype[,-1], myPhenotype[,-1])

```


```{r}
plotManhatten(P)
plotManhatten(P2)
```


Returns: a QQ plot of observed and expected p values
```{r, Plot_QQ}
par(mfrow=c(1,2))
plotQQ(P)
plotQQ(P2)
```
