#' Analyze_Model_Quality
#'
#' Assess the quality of a model.
#' Returns the number of True Positives above the first False Positive
#'
#' @param P A p-value vector (n) generated by a Model
#' @param QTN.position position of significant GCNs
#'
#' @return
#' @example
Analyze_Model_Quality <- function(P, QTN.position)
{

  # index=order(p)
  # top10=index[1:10]
  # detected=intersect(top10,QTN.position)
  # falsePositive=setdiff(top10,QTN.position)
  # top10
  # QTN.position
  # detected
  # length(detected)
  # falsePositive


  return(quality)
}
