#' pcThreshold
#'
#' Determines principle components to use in model based on set threshold
#'
#' @param PC principle components generated by prcomp
#' @param threshold the amount a principle component must explain to be kept in the model
#'
#' @return PC_T
#' @export
pcThreshold <- function(PC, threshold = 0.014)
{
  summaryPCA = summary(PC)

  pcano = min(which(summaryPCA$importance[2,] < threshold))

  PC_T = PC$x[,1:pcano]
  return(PC_T)
}
